name: Permission check
on:
  pull_request_target:
    paths:
      - '**/run'
      - '**/finish'
      - '**/check'
      - 'root/migrations/*'

jobs:
  permission_check:
    uses: linuxserver/github-workflows/.github/workflows/init-svc-executable-permissions.yml@5d69252151b995b99ea9d883b73e5be5a82d88cf # v1
